- hosts: localhost
  become: true

  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/pip.yml
    - name: Executing user-specific operations
      block:
      - include: tasks/git.yml
      become: yes
      become_user: "{{ username }}"
