- hosts: localhost
  become: true

  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/pip.yml
    - include: tasks/powerline.yml

    - name: Desktop settings
      block:
      - include: tasks/desktop-packages.yml
      when: is_desktop

    - name: Executing user-specific operations
      block:
      - include: tasks/git.yml
      - include: tasks/vim.yml
      become: yes
      become_user: "{{ username }}"
