- name: Set git global config
  become: yes
  become_user: "{{ username }}"
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: "user.name", value: "{{ git_user_name }}" }
    - { name: "user.email", value: "{{ git_user_email }}" }
    - { name: "gitreview.username", value: "{{ git_review_name }}" }
    - { name: "core.editor", value: "vim" }
    - { name: "push.default", value: "simple" }
    - { name: "color.ui", value: "auto" }
    - { name: "hub.protocol", value: "ssh" }
