- name: Install system packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - htop
    - libselinux-python
    - libsemanage-python
    - gimp
    - gcc
    - python-virtualenv
    - openssl-devel
    - gcc
    - libffi-devel
    - libxslt-devel
    - mysql-devel
    - python35
