- name: Create ansible user
  user: name=ansible uid=900

- name: Enable ansible sudo
  copy: src=files/sudoers_ansible dest=/etc/sudoers.d/ansible owner=root group=root mode=0440

- name: Make sure user account is present
  user:
    name: smcginnis
    comment: Sean McGinnis
    shell: /bin/bash
    group: smcginnis
    state: present

- name: Enable sudo for user account
  template:
    src: files/sudoers.j2
    dest: "/etc/sudoers.d/{{ username }}"
    owner: root
    group: root
    mode: 0440
